# Generated by Django 4.2.1 on 2023-05-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_category_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='posts', to='post.category'),
        ),
    ]
